* Descripción del sistema
  
El proyecto resuelve el problema de logística y tratamiento del producto gracias a un almacén automatizado de reparto de prensa. El flujo de trabajo empieza en la cinta principal. En primer lugar, entran paquetes por la cinta, que son más tarde escaneados por un lector de códigos QR (embebido en el lector de posición de final de la cinta) para poder clasificarse posteriormente. Seguidamente, al llegar a la plataforma giratoria, dependiendo del tipo de paquete se traslada a la cinta A, B o C, donde se le aplican sendos procesos según el tipo de paquete (encartado, flejado o embolsado). Luego son llevados a una cinta común (cinta intermedia). Al final de esta cinta se encuentra un cruce (recurso compartido) donde se decide qué paquete pasa en función de un orden de prioridad previamente asignado (es prioritario el paquete B, luego el A y por último el C). Al final de la cinta intermedia un brazo mecánico se encargará de trasladar los paquetes a las cintas finales (cintas 1, 2 y 3) que conectan con los respectivos almacenes (A, B y C). Desde aquí tres AGV irán cogiendo los tres tipos de paquetes. Cada AGV tiene asignado un solo tipo de paquete, que luego irá depositando en los tres camiones dependiendo de los pedidos de cada camión.

* Objetivos de control

  El objetivo es que los paquetes que van entrando por la cinta principal (se activan manualmente con el botón "Paquete") acaben cargados en los camiones de acuerdo a los pedidos que éstos realicen.

* Modos de funcionamiento

  El modo de funcionamiento por defecto es el modo automático, en el que todo el proceso desde que se pulsa el botón "Paquete" hasta la carga en el camión es automático. Por otra parte tenemos el modo manual, a través del cual se pueden manejar todos los actuadores de la planta a través de la interfaz HMI, implementada en las botoneras "Botonera_alm_agv" y "Botonera_cin_gru". Por último hemos decidido meter un modo "pausa" que, a diferencia del marcha/paro, deja la planta paralizada en el estado que estuviera hasta que se desactive el modo.

* Explicación de la visualización

  Hemos decidido implementar los sensores con forma triangular o cuadrada y un código de colores dual. Cuando están desactivados se muestran en rojo, y al activarse pasan a estar coloreados en verde hasta que se vuelven a desactivar. Por otra parte hemos incluido indicadores visuales que permiten ver de forma fácil qué cintas o procesos están activados en cada momento. Estos indicadores se muestran en blanco cuando su actuador correspondiente está desactivado y en azul en caso contrario. También tenemos un semáforo en el cruce de las cintas A, B y C con la cinta intermedia, que permite ver si el cruce está o no ocupado.
